name: Validate action typing

on:
  push:
    paths:
      - 'action.yml'
      - 'action-types.yml'
  workflow_dispatch:
jobs:
  validate-typings:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: typesafegithub/github-actions-typing@v1